apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-boot-app
  labels:
    app: spring-boot-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: spring-boot-app
  template:
    metadata:
      labels:
        app: spring-boot-app
    spec:
      terminationGracePeriodSeconds: 30
      containers:
        - name: spring-boot-app
          image: hardikjain2098/spring-boot-app:spring-boot-app
          imagePullPolicy: Always
          ports:
            - containerPort: 9000
          env:
            - name: PORT
              value: "9000"
---
apiVersion: v1
kind: Service
metadata:
  name: spring-boot-app-service
spec:
  selector:
    app: spring-boot-app
  type: LoadBalancer
  ports:
    - port: 9000
      targetPort: 9000
